insert into student(name,email) values('Nancy Thompson','nthompson1g@seesaa.net');
insert into student(name,email) values('Sarah Stanley','sstanley1h@google.ru');
insert into student(name,email) values('Douglas Gardner','dgardner1i@jugem.jp');
insert into student(name,email) values('Mark Thomas','mthomas1j@deviantart.com');
insert into student(name,email) values('Judith Jenkins','jjenkins1k@nps.gov');
insert into student(name,email) values('Henry Ross','hross1l@chicagotribune.com');
insert into student(name,email) values('Kimberly Gomez','kgomez1m@blog.com');
insert into student(name,email) values('Pamela Nelson','pnelson1n@marketwatch.com');
insert into student(name,email) values('Elizabeth Sanchez','esanchez1o@artisteer.com ');
insert into student(name,email) values('Charles Fuller','cfuller1p@google.com.hk ');
insert into student(name,email) values('Andrew Stewart','astewart1q@nature.com');
insert into student(name,email) values('Maria Kennedy','mkennedy1r@economist.com');
insert into student(name,email) values('Clarence Ferguson','cferguson1s@gnu.org ');
insert into student(name,email) values('Annie Campbell','acampbell1t@alexa.com');
insert into student(name,email) values('Jeremy Wilson','jwilson1u@ca.gov');
insert into student(name,email) values('Jeremy Ward','jward1v@dmoz.org');
insert into student(name,email) values('Peter Brown','pbrown1w@liveinternet.ru ');
insert into student(name,email) values('Laura Stewart','lstewart1x@google.it');
insert into student(name,email) values('Christina Montgomery','cmontgomery1y@free.fr');
insert into student(name,email) values('Amy Bishop','abishop1z@exblog.jp');
insert into student(name,email) values('Jeffrey Pierce','jpierce20@usnews.com');
insert into student(name,email) values('Virginia Welch','vwelch21@wunderground.com');
insert into student(name,email) values('Beverly Lane','blane22@amazon.com');
insert into student(name,email) values('Norma Howard','nhoward23@imgur.com');
insert into student(name,email) values('Margaret Kelley','mkelley24@imageshack.us');
insert into student(name,email) values('Brenda Miller','bmiller25@technorati.com');
insert into student(name,email) values('Catherine White','cwhite26@google.ru');
insert into student(name,email) values('Mary Berry','mberry27@freewebs.com');
insert into student(name,email) values('Sarah Young','syoung28@digg.com');
insert into student(name,email) values('Craig Moreno','cmoreno29@paypal.com');
insert into student(name,email) values('Louise Fisher','lfisher2a@github.com');
insert into student(name,email) values('Carol Ray','cray2b@wp.com');
insert into student(name,email) values('Sean Bishop','sbishop2c@geocities.com');
insert into student(name,email) values('Joseph Weaver','jweaver2d@nature.com');
insert into student(name,email) values('Louise Ramos','lramos2e@mit.edu');
insert into student(name,email) values('Brian Carpenter','bcarpenter2f@eepurl.com');